### ISSUE TITLE
only titles without a text body

### ISSUE THREAD

**Issue by StevaMan** [tanriol/digest#49] opened 2013-06-27 04:44 UTC
![digest error](https://f.cloud.github.com/assets/4845244/713903/03704d74-dee4-11e2-92ee-248263861f4b.png)
this is taken from nightly 25.0a1...i know that is a new version, but if you can tell me what to do...:-)

**Comment by tanriol** [comment] 2013-06-27 05:38
I'm using Nightly and see no problems adding the InsideHW feeds.
What's the problem? Do you see item titles only or nothing at all in the right part of the screen?

Do you see the text telling that there are no items?
Have you entered something in the search bar or enabled "starred-only" mode with the star button in the top right corner?

This is my testing Digest
![screenshot - 270613 - 09 39 53](https://f.cloud.github.com/assets/1027034/714018/211d0436-deec-11e2-96fe-fa79d04f8208.png)

**Comment by StevaMan** [comment] 2013-06-27 05:48
i don't see anything in the right side of the screen...there is no title, or the text you just saw...
there is no text telling about the problem, and no change for any other feed on the list...
star mode is not used or search option...

sorry for my poor english :-)

**Comment by tanriol** [comment] 2013-06-27 06:04
@StevaMan, could you please try the following:
- open Digest tab
- open Web console (Ctrl+Shift+K)
- press "Clear" button
- select another feed in the sidebar
- note the error and/or warning messages (the one about "XUL box ... contained an inline #text child" is well-known, but unrelated)
- paste the following in the console's command line in the bottom and tell me the results
  
  `String([v.id for (v in gCurrentView._entryViews)])`
  
  `String(gCurrentView._loadedEntries)`

**Comment by StevaMan** [comment] 2013-06-27 06:16
![digest error](https://f.cloud.github.com/assets/4845244/714112/e66dbd44-def0-11e2-9c6c-65f0be31878d.png)

same result with one by one command entered below...

**Comment by tanriol** [comment] 2013-06-27 06:58
First, thanks for reporting. I've seen reports of this bug for Brief, but was unable to reproduce it.

Do I understand correctly that it happens every time? Refreshing page and restarting Firefox do not get rid of it?

This may be a DIgest database corruption. Assuming the feeds you have used are public and do not contain private information, could I ask you to send me the database so that I could analyze it locally and try to find the corruption source? It consists of three files brief.sqlite, brief.sqlite-shm and brief.sqlite-wal, located in your Firefox profile directory. My e-mail is dennis.lissov@gmail.com

**Comment by StevaMan** [comment] 2013-06-27 07:13
thank you for support and patience :-)
restarting/reinstalling firefox did not helped...maybe i have a problem because i install some nightly x86 version while ago !?!?!?

attach has been sent :-)

**Comment by tanriol** [comment] 2013-06-27 08:19
Thank you very much. Now I can reproduce it and start searching for its cause.

**Comment by tanriol** [comment] 2013-06-27 08:56
Unfortunately, this is really a database corruption bug. The entries' properties and contents are still available, but it's not possible to match properties (including the entries' original feeds) to titles and contents.

It seems that during some modifications the `rowid` column in the `entries_text` table was reset. I'll try to find the conditions under which this may happen.

Do I understand correctly that you have done at least one of the following:
- deleted a whole feed,
- deleted some entries directly,
- emptied Trash?

**Comment by StevaMan** [comment] 2013-06-27 09:13
usually i just click on the arrow right next to the title, and then delete button right ahead...then i just delete whole unread section and then empty the trash...i did this all the time, very often :-)

**Comment by tanriol** [comment] 2013-06-27 11:50
OK, if it's not a strange sqlite bug, the problem seems to be that at some moment all entries from the `entries_text` table were deleted. However, this should not happen.
Digest removes them from the database only after either:
- the feed was deleted over 1 week ago, or
- the entry is deleted _and_ older than the oldest one fetched last time.

These together should ensure that the current items are never deleted, unless probably one of the following happend:
- all the feeds were deleted for over a week, or
- all the feeds were deleted and time jumped a week ahead, or
- time jumped in some strange way during update.

I currently don't see a way to cause this without time jumps or long-unused Digest.

I'm going to fix it by the next release.

**Comment by StevaMan** [comment] 2013-06-27 12:21
this is the best sw support i have ever seen :+1:

**Comment by tanriol** [comment] 2013-07-02 20:04
Should be fixed or at least sidestepped now.

**Closed as completed by tanriol** 2013-07-02 20:04 UTC
Labels: bug, data loss

**Comment by Infocatcher** [comment] 2013-07-03 16:30
Something went wrong after last patches: I see 122 unreaded items in the counter (looks correct), but only 5 in the list.

And Digest 1.0.3 correctly works with the same brief.sqlite.

**Comment by tanriol** [comment] 2013-07-03 17:45
Hmmm... very strange. I cannot reproduce this. If you could send the brief.sqlite and brief.sqlite-wal to redacted@email, I'll look into it in more details.

**Comment by Infocatcher** [comment] 2013-07-03 18:12
> If you could send ...

Done. :)
(I already mark some entries as readed, but still can reproduce described bug)

**Comment by tanriol** [comment] 2013-07-03 19:16
In a private discussion this was found to be a misapplied custom patch and not related to this issue.

**Comment by Infocatcher** [comment] 2013-07-03 19:18
Yes, sorry for wrong report.
