### ISSUE TITLE
Does not support this rss.xml

### ISSUE THREAD

**Issue by kid23** [tanriol/digest#40] opened 2013-06-12 13:58 UTC
for example: from http://www.dmzj.com/z/zhihoudeevangelion/rss.xml

<item><title><![CDATA[之后的Evangelion：爱~~动漫之家漫画网]]></title><link><![CDATA[/zhihoudeevangelion/16823.shtml?from=rssReader]]></link><pubDate><![CDATA[Mon, 31 Oct 2011 11:23:36 +0800]]></pubDate><author><![CDATA[しづきみちる]]></author><source url="http://www.dmzj.com"><![CDATA[动漫之家漫画网]]></source><description><![CDATA[<a href='/zhihoudeevangelion/16823.shtml?from=rssReader' target='_blank'><img src='http://imgfast.dmzj.com/webpic/8/zhihoudeEvangelion.jpg' width='150' height='200'/></a></br><a href='/zhihoudeevangelion/16823.shtml?from=rssReader' title='第07卷' target='_blank'>第07卷</a>]]></description></item>

It's not shown as a link in the feed view. The link in the detail view shows like resource://digest-content/*********************from=rssReader. 
I think its missing domain name in the digest.

**Comment by tanriol** [comment] 2013-06-12 19:05
Thanks for reporting.
This is a known problem for a long time (bug #9). I don't have a solution yet.
Closing as a duplicate of an existing bug.

**Closed as completed by tanriol** 2013-06-12 19:05 UTC
Labels: bug, duplicate
